spring.application.name=Industrial_Project-Insurance_System

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/insurancedb
spring.datasource.username=Practice
spring.datasource.password=Ratan@_#1425
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080


#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/InsuranceSystem
#spring.datasource.username=root
#spring.datasource.password=root@123
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#server.port=8686